FROM postgres:latest

ENV POSTGRES_DB websitenamepics
ENV POSTGRES_USER website
ENV POSTGRES_PASSWORD EE776noc1!

RUN apt-get update && apt-get install -y \
    vim

COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 5432

CMD ["postgres"]
