# Use an official Python runtime as a parent image
FROM python:3.8

# Set the working directory to /app
WORKDIR /app

# Copy the requirements file into the container at /app
COPY app/requirements.txt .

# Install any needed packages specified in requirements.txt
RUN apt-get update && apt-get install -y postgresql-server-dev-all
RUN pip install --no-cache-dir -r requirements.txt

# Copy the current directory contents into the container at /app
COPY app/ /app

WORKDIR /app
# Make port 3001 available to the world outside this container
EXPOSE 3001

WORKDIR /app
# Define environment variable
ENV FLASK_APP=main.py

WORKDIR /app
# Run main.py when the container launches
CMD ["flask", "run", "--host=0.0.0.0", "--port=3001"]
